{
 "title": "Infrastructure",
 "description": "Monitor Docker containers, CPU, memory and uptime",
 "tags": [
  "infra",
  "docker",
  "monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Container CPU Usage Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[1m])) by (container_label_com_docker_swarm_service_name)"
    }
   ]
  },
  {
   "title": "Container Memory Usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes) by (container_label_com_docker_swarm_service_name)"
    }
   ]
  },
  {
   "title": "Services Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count(up{job=~\"prometheus|mock-metrics|jenkins|cadvisor\"})"
    }
   ]
  },
  {
   "title": "Services Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "targets": [
    { "expr": "sum(up) by (job)" }
   ]
  },
  {
   "title": "Service Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  }
 ]
}